### ISSUE TITLE
GitHub OAuth App + oauth2-proxy + s3-proxy

### ISSUE THREAD

**Issue by yteraoka** [yteraoka/blog-1q77-com#147]
## OAuth2 Proxy

https://oauth2-proxy.github.io/oauth2-proxy/

```bash
./oauth2-proxy \
  --provider=github \
  --github-user=yteraoka \
  --client-id=${GITHUB_OAUTH_APP_CLIENT_ID} \
  --client-secret=${GITHUB_OAUTH_APP_CLIENT_SECRET} \
  --cookie-secret=${COOKIE_SECRET} \
  --email-domain=\* \
  --http-address=0.0.0.0:8080 \
  --upstream=http://127.0.0.1:8000 \
  --redirect-url=http://localhost:8080/oauth2/callback \
  --scope=user:email \
  --cookie-secure=false
```

cookie-secret はランダムな文字列で 16, 24, 32 bytes のいずれかの長さで指定する。

## S3 Proxy

https://oxyno-zeta.github.io/s3-proxy/

```yaml
log:
  level: info
  format: test

server:
  listenAddr: ""
  port: 8000
  timeouts:
    readTimeout: 5s
    readHeaderTimeout: 10s
    writeTimeout: 60s
    idleTimeout: 10s
  compress:
    enabled: false

targets:
  first-bucket:
    mount:
      path:
        - /
      actions:
        GET:
          enabled: true
        PUT:
          enabled: false
        DELETE:
          enabled: false
    bucket:
      name: ${S3_BUCKET_NAME}
      prefix: ""
      region: ap-northeast-1
      disableSSL: false
```
